/** Fluxo BPMN oficial da Rodada de Parcerias FL Insider. */
export const fluxoParceriasBpmn = `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_Parcerias" targetNamespace="https://flinsider.com.br/parcerias">
  <bpmn:process id="Processo_Parcerias" name="Rodada de Parcerias FL Insider" isExecutable="false">
    <bpmn:laneSet id="Lanes_Parcerias">
      <bpmn:lane id="Lane_Expert" name="Expert"><bpmn:flowNodeRef>Start_Cadastro</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_PreencherCadastro</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_EnviarProjeto</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_AjustarProjeto</bpmn:flowNodeRef></bpmn:lane>
      <bpmn:lane id="Lane_Operacao" name="Operação FL Insider"><bpmn:flowNodeRef>Task_ConferirDados</bpmn:flowNodeRef><bpmn:flowNodeRef>Gateway_DadosCompletos</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_SolicitarAjustes</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_TriagemManual</bpmn:flowNodeRef><bpmn:flowNodeRef>Gateway_Elegivel</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_PublicarCatalogo</bpmn:flowNodeRef><bpmn:flowNodeRef>End_NaoElegivel</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_OrganizarReuniao</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_ConfirmarAgenda</bpmn:flowNodeRef></bpmn:lane>
      <bpmn:lane id="Lane_Lancador" name="Lançador"><bpmn:flowNodeRef>Task_ExplorarCatalogo</bpmn:flowNodeRef><bpmn:flowNodeRef>Task_DeclararInteresse</bpmn:flowNodeRef><bpmn:flowNodeRef>End_ReuniaoConfirmada</bpmn:flowNodeRef></bpmn:lane>
    </bpmn:laneSet>
    <bpmn:startEvent id="Start_Cadastro" name="Início"><bpmn:outgoing>Flow_Start_Preencher</bpmn:outgoing></bpmn:startEvent>
    <bpmn:userTask id="Task_PreencherCadastro" name="Preencher cadastro e projeto"><bpmn:incoming>Flow_Start_Preencher</bpmn:incoming><bpmn:outgoing>Flow_Preencher_Enviar</bpmn:outgoing></bpmn:userTask>
    <bpmn:userTask id="Task_EnviarProjeto" name="Enviar projeto para validação"><bpmn:incoming>Flow_Preencher_Enviar</bpmn:incoming><bpmn:incoming>Flow_Ajustar_Enviar</bpmn:incoming><bpmn:outgoing>Flow_Enviar_Conferir</bpmn:outgoing></bpmn:userTask>
    <bpmn:userTask id="Task_AjustarProjeto" name="Ajustar projeto"><bpmn:incoming>Flow_Solicitar_Ajustar</bpmn:incoming><bpmn:outgoing>Flow_Ajustar_Enviar</bpmn:outgoing></bpmn:userTask>
    <bpmn:userTask id="Task_ConferirDados" name="Conferir cadastro"><bpmn:incoming>Flow_Enviar_Conferir</bpmn:incoming><bpmn:outgoing>Flow_Conferir_Gateway</bpmn:outgoing></bpmn:userTask>
    <bpmn:exclusiveGateway id="Gateway_DadosCompletos" name="Dados completos?"><bpmn:incoming>Flow_Conferir_Gateway</bpmn:incoming><bpmn:outgoing>Flow_Dados_Nao</bpmn:outgoing><bpmn:outgoing>Flow_Dados_Sim</bpmn:outgoing></bpmn:exclusiveGateway>
    <bpmn:userTask id="Task_SolicitarAjustes" name="Solicitar ajustes"><bpmn:incoming>Flow_Dados_Nao</bpmn:incoming><bpmn:outgoing>Flow_Solicitar_Ajustar</bpmn:outgoing></bpmn:userTask>
    <bpmn:userTask id="Task_TriagemManual" name="Triagem: Nicho, Avatar, ROMA e maturidade"><bpmn:incoming>Flow_Dados_Sim</bpmn:incoming><bpmn:outgoing>Flow_Triagem_Elegivel</bpmn:outgoing></bpmn:userTask>
    <bpmn:exclusiveGateway id="Gateway_Elegivel" name="Projeto elegível?"><bpmn:incoming>Flow_Triagem_Elegivel</bpmn:incoming><bpmn:outgoing>Flow_Elegivel_Nao</bpmn:outgoing><bpmn:outgoing>Flow_Elegivel_Sim</bpmn:outgoing></bpmn:exclusiveGateway>
    <bpmn:endEvent id="End_NaoElegivel" name="Encerrar / devolver"><bpmn:incoming>Flow_Elegivel_Nao</bpmn:incoming></bpmn:endEvent>
    <bpmn:serviceTask id="Task_PublicarCatalogo" name="Publicar no catálogo"><bpmn:incoming>Flow_Elegivel_Sim</bpmn:incoming><bpmn:outgoing>Flow_Publicar_Explorar</bpmn:outgoing></bpmn:serviceTask>
    <bpmn:userTask id="Task_ExplorarCatalogo" name="Explorar projetos elegíveis"><bpmn:incoming>Flow_Publicar_Explorar</bpmn:incoming><bpmn:outgoing>Flow_Explorar_Interesse</bpmn:outgoing></bpmn:userTask>
    <bpmn:userTask id="Task_DeclararInteresse" name="Declarar interesse em reunião"><bpmn:incoming>Flow_Explorar_Interesse</bpmn:incoming><bpmn:outgoing>Flow_Interesse_Organizar</bpmn:outgoing></bpmn:userTask>
    <bpmn:userTask id="Task_OrganizarReuniao" name="Organizar horário e mesa"><bpmn:incoming>Flow_Interesse_Organizar</bpmn:incoming><bpmn:outgoing>Flow_Organizar_Confirmar</bpmn:outgoing></bpmn:userTask>
    <bpmn:sendTask id="Task_ConfirmarAgenda" name="Confirmar agenda com as partes"><bpmn:incoming>Flow_Organizar_Confirmar</bpmn:incoming><bpmn:outgoing>Flow_Confirmar_Fim</bpmn:outgoing></bpmn:sendTask>
    <bpmn:endEvent id="End_ReuniaoConfirmada" name="Reunião presencial confirmada"><bpmn:incoming>Flow_Confirmar_Fim</bpmn:incoming></bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_Start_Preencher" sourceRef="Start_Cadastro" targetRef="Task_PreencherCadastro" /><bpmn:sequenceFlow id="Flow_Preencher_Enviar" sourceRef="Task_PreencherCadastro" targetRef="Task_EnviarProjeto" /><bpmn:sequenceFlow id="Flow_Ajustar_Enviar" sourceRef="Task_AjustarProjeto" targetRef="Task_EnviarProjeto" /><bpmn:sequenceFlow id="Flow_Enviar_Conferir" sourceRef="Task_EnviarProjeto" targetRef="Task_ConferirDados" /><bpmn:sequenceFlow id="Flow_Conferir_Gateway" sourceRef="Task_ConferirDados" targetRef="Gateway_DadosCompletos" /><bpmn:sequenceFlow id="Flow_Dados_Nao" name="Não" sourceRef="Gateway_DadosCompletos" targetRef="Task_SolicitarAjustes" /><bpmn:sequenceFlow id="Flow_Dados_Sim" name="Sim" sourceRef="Gateway_DadosCompletos" targetRef="Task_TriagemManual" /><bpmn:sequenceFlow id="Flow_Solicitar_Ajustar" sourceRef="Task_SolicitarAjustes" targetRef="Task_AjustarProjeto" /><bpmn:sequenceFlow id="Flow_Triagem_Elegivel" sourceRef="Task_TriagemManual" targetRef="Gateway_Elegivel" /><bpmn:sequenceFlow id="Flow_Elegivel_Nao" name="Não" sourceRef="Gateway_Elegivel" targetRef="End_NaoElegivel" /><bpmn:sequenceFlow id="Flow_Elegivel_Sim" name="Sim" sourceRef="Gateway_Elegivel" targetRef="Task_PublicarCatalogo" /><bpmn:sequenceFlow id="Flow_Publicar_Explorar" sourceRef="Task_PublicarCatalogo" targetRef="Task_ExplorarCatalogo" /><bpmn:sequenceFlow id="Flow_Explorar_Interesse" sourceRef="Task_ExplorarCatalogo" targetRef="Task_DeclararInteresse" /><bpmn:sequenceFlow id="Flow_Interesse_Organizar" sourceRef="Task_DeclararInteresse" targetRef="Task_OrganizarReuniao" /><bpmn:sequenceFlow id="Flow_Organizar_Confirmar" sourceRef="Task_OrganizarReuniao" targetRef="Task_ConfirmarAgenda" /><bpmn:sequenceFlow id="Flow_Confirmar_Fim" sourceRef="Task_ConfirmarAgenda" targetRef="End_ReuniaoConfirmada" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="Diagram_Parcerias"><bpmndi:BPMNPlane id="Plane_Parcerias" bpmnElement="Processo_Parcerias">
    <bpmndi:BPMNShape id="Lane_Expert_di" bpmnElement="Lane_Expert" isHorizontal="true"><dc:Bounds x="80" y="70" width="1780" height="150" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Lane_Operacao_di" bpmnElement="Lane_Operacao" isHorizontal="true"><dc:Bounds x="80" y="220" width="1780" height="170" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Lane_Lancador_di" bpmnElement="Lane_Lancador" isHorizontal="true"><dc:Bounds x="80" y="390" width="1780" height="150" /></bpmndi:BPMNShape>
    <bpmndi:BPMNShape id="Start_Cadastro_di" bpmnElement="Start_Cadastro"><dc:Bounds x="120" y="127" width="36" height="36" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_PreencherCadastro_di" bpmnElement="Task_PreencherCadastro"><dc:Bounds x="185" y="105" width="140" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_EnviarProjeto_di" bpmnElement="Task_EnviarProjeto"><dc:Bounds x="370" y="105" width="150" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_AjustarProjeto_di" bpmnElement="Task_AjustarProjeto"><dc:Bounds x="710" y="105" width="135" height="80" /></bpmndi:BPMNShape>
    <bpmndi:BPMNShape id="Task_ConferirDados_di" bpmnElement="Task_ConferirDados"><dc:Bounds x="550" y="263" width="130" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Gateway_DadosCompletos_di" bpmnElement="Gateway_DadosCompletos" isMarkerVisible="true"><dc:Bounds x="720" y="278" width="50" height="50" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_SolicitarAjustes_di" bpmnElement="Task_SolicitarAjustes"><dc:Bounds x="800" y="263" width="135" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_TriagemManual_di" bpmnElement="Task_TriagemManual"><dc:Bounds x="830" y="263" width="165" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Gateway_Elegivel_di" bpmnElement="Gateway_Elegivel" isMarkerVisible="true"><dc:Bounds x="1035" y="278" width="50" height="50" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="End_NaoElegivel_di" bpmnElement="End_NaoElegivel"><dc:Bounds x="1095" y="325" width="36" height="36" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_PublicarCatalogo_di" bpmnElement="Task_PublicarCatalogo"><dc:Bounds x="1125" y="263" width="145" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_OrganizarReuniao_di" bpmnElement="Task_OrganizarReuniao"><dc:Bounds x="1500" y="263" width="150" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_ConfirmarAgenda_di" bpmnElement="Task_ConfirmarAgenda"><dc:Bounds x="1690" y="263" width="130" height="80" /></bpmndi:BPMNShape>
    <bpmndi:BPMNShape id="Task_ExplorarCatalogo_di" bpmnElement="Task_ExplorarCatalogo"><dc:Bounds x="1260" y="425" width="150" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="Task_DeclararInteresse_di" bpmnElement="Task_DeclararInteresse"><dc:Bounds x="1450" y="425" width="150" height="80" /></bpmndi:BPMNShape><bpmndi:BPMNShape id="End_ReuniaoConfirmada_di" bpmnElement="End_ReuniaoConfirmada"><dc:Bounds x="1740" y="447" width="36" height="36" /></bpmndi:BPMNShape>
    <bpmndi:BPMNEdge id="Flow_Start_Preencher_di" bpmnElement="Flow_Start_Preencher"><di:waypoint x="156" y="145" /><di:waypoint x="185" y="145" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Preencher_Enviar_di" bpmnElement="Flow_Preencher_Enviar"><di:waypoint x="325" y="145" /><di:waypoint x="370" y="145" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Enviar_Conferir_di" bpmnElement="Flow_Enviar_Conferir"><di:waypoint x="520" y="145" /><di:waypoint x="540" y="145" /><di:waypoint x="540" y="303" /><di:waypoint x="550" y="303" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Conferir_Gateway_di" bpmnElement="Flow_Conferir_Gateway"><di:waypoint x="680" y="303" /><di:waypoint x="720" y="303" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Dados_Nao_di" bpmnElement="Flow_Dados_Nao"><di:waypoint x="770" y="303" /><di:waypoint x="800" y="303" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Solicitar_Ajustar_di" bpmnElement="Flow_Solicitar_Ajustar"><di:waypoint x="868" y="263" /><di:waypoint x="868" y="230" /><di:waypoint x="778" y="230" /><di:waypoint x="778" y="185" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Ajustar_Enviar_di" bpmnElement="Flow_Ajustar_Enviar"><di:waypoint x="710" y="145" /><di:waypoint x="520" y="145" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Dados_Sim_di" bpmnElement="Flow_Dados_Sim"><di:waypoint x="745" y="328" /><di:waypoint x="745" y="360" /><di:waypoint x="812" y="360" /><di:waypoint x="812" y="303" /><di:waypoint x="830" y="303" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Triagem_Elegivel_di" bpmnElement="Flow_Triagem_Elegivel"><di:waypoint x="995" y="303" /><di:waypoint x="1035" y="303" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Elegivel_Nao_di" bpmnElement="Flow_Elegivel_Nao"><di:waypoint x="1060" y="328" /><di:waypoint x="1113" y="328" /><di:waypoint x="1113" y="325" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Elegivel_Sim_di" bpmnElement="Flow_Elegivel_Sim"><di:waypoint x="1085" y="303" /><di:waypoint x="1125" y="303" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Publicar_Explorar_di" bpmnElement="Flow_Publicar_Explorar"><di:waypoint x="1270" y="303" /><di:waypoint x="1335" y="303" /><di:waypoint x="1335" y="425" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Explorar_Interesse_di" bpmnElement="Flow_Explorar_Interesse"><di:waypoint x="1410" y="465" /><di:waypoint x="1450" y="465" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Interesse_Organizar_di" bpmnElement="Flow_Interesse_Organizar"><di:waypoint x="1600" y="465" /><di:waypoint x="1620" y="465" /><di:waypoint x="1620" y="385" /><di:waypoint x="1575" y="385" /><di:waypoint x="1575" y="343" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Organizar_Confirmar_di" bpmnElement="Flow_Organizar_Confirmar"><di:waypoint x="1650" y="303" /><di:waypoint x="1690" y="303" /></bpmndi:BPMNEdge><bpmndi:BPMNEdge id="Flow_Confirmar_Fim_di" bpmnElement="Flow_Confirmar_Fim"><di:waypoint x="1755" y="343" /><di:waypoint x="1755" y="447" /></bpmndi:BPMNEdge>
  </bpmndi:BPMNPlane></bpmndi:BPMNDiagram>
</bpmn:definitions>`;
