/** Painel Expert — FL Insider v4: projeto próprio e reuniões, sem exposição de Lançadores. */
import { useMemo, useState } from "react";
import { experts, interesses } from "@/lib/mockData";
import PainelLayout from "@/components/PainelLayout";
import { BadgeStatus, ChecklistTriagem, FotoPerfil, InstagramHandle, Label } from "@/components/Compartilhados";
import { CalendarClock, FileText, LockKeyhole, MapPin } from "lucide-react";
import CadastroProjeto from "./CadastroProjeto";

const MEU_EXPERT_ID = "exp-1";
const usuarios = { admin: "Ana — Administradora", expert: "Marina Valle — Expert", lancador: "Juliana Ferreira — Lançadora" };

export default function ExpertPainel({ onTrocarPapel }: { onTrocarPapel: (p: "admin" | "expert" | "lancador") => void }) {
  const [pagina, setPagina] = useState(() => new URLSearchParams(window.location.search).get("aba") === "cadastro" ? "cadastro" : "meu-projeto");
  const expert = experts.find((item) => item.id === MEU_EXPERT_ID)!;
  const minhasReunioes = useMemo(() => interesses.filter((interesse) => interesse.expertId === MEU_EXPERT_ID), []);
  const projeto = expert.projeto;
  return <PainelLayout papel="expert" onTrocarPapel={onTrocarPapel} nomeUsuario={usuarios.expert} paginaAtiva={pagina} onNavegar={setPagina}
    titulo={pagina === "meu-projeto" ? "Meu projeto" : pagina === "cadastro" ? "Cadastro do projeto" : "Minhas reuniões"}
    subtitulo={pagina === "meu-projeto" ? "Acompanhe sua ROMA, Avatar e a validação da operação" : pagina === "cadastro" ? "Protótipo visual para validar os campos com a operação" : "A organização confirma os horários da Rodada de Parcerias"}>
    {pagina === "meu-projeto" && <section className="space-y-6 rise-in"><div className="bg-card border border-border rounded-lg p-6 flex flex-col sm:flex-row sm:items-center gap-4"><FotoPerfil src={expert.fotoUrl} alt={expert.nome} size="lg" /><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-xl font-semibold">{expert.nome}</h2><BadgeStatus status={expert.statusCadastro} /></div><p className="text-sm text-muted-foreground">{expert.cargo} · {expert.nivel}</p><InstagramHandle handle={expert.instagram} /></div></div>
      <article className="bg-card border border-border rounded-lg overflow-hidden"><div className="px-6 py-4 border-b border-border bg-secondary/60 flex flex-wrap gap-2 justify-between"><div className="flex items-center gap-2"><FileText className="size-4 text-primary" /><h3 className="font-display font-semibold">{projeto.nome}</h3></div><BadgeStatus status={projeto.status} /></div><div className="p-6 space-y-6"><div><Label>ROMA — a transformação do seu produto</Label><p className="font-display text-xl mt-2">{projeto.roma}</p></div><div className="grid md:grid-cols-2 gap-6"><div><Label>Avatar</Label><p className="text-sm mt-2">{projeto.avatar.quem}</p><div className="mt-3 space-y-1.5">{projeto.avatar.dores.map((dor) => <p key={dor} className="text-sm text-muted-foreground pl-3 border-l-2 border-primary/40">Dor: {dor}</p>)}<p className="text-sm mt-3"><strong>Ambição:</strong> {projeto.avatar.ambicao}</p></div></div><div className="space-y-3"><div><Label>Nicho</Label><p className="text-sm mt-1">{projeto.nicho}</p></div><div><Label>Maturidade</Label><p className="text-sm mt-1">{projeto.maturidade}</p></div><div><Label>Especialidades</Label><p className="text-sm mt-1">{projeto.especialidades.join(" · ")}</p></div></div></div><div className="rounded-lg bg-accent/45 border border-border p-4"><Label>Triagem manual</Label><div className="mt-3"><ChecklistTriagem triagem={projeto.triagem} /></div><p className="text-sm text-muted-foreground mt-3">{projeto.triagem.observacao}</p></div></div></article>
      <div className="bg-muted/50 border border-border rounded-lg p-5 flex gap-3"><LockKeyhole className="size-5 text-muted-foreground shrink-0" /><p className="text-sm text-muted-foreground">Os dados de Lançadores não ficam visíveis neste painel. A organização prioriza a conversa presencial na Rodada de Parcerias e compartilha apenas as informações necessárias quando uma reunião é confirmada.</p></div>
    </section>}
    {pagina === "cadastro" && <CadastroProjeto />}
    {pagina === "reunioes" && <section className="space-y-4 rise-in">{minhasReunioes.length === 0 ? <div className="bg-card border border-border rounded-lg p-8 text-center"><CalendarClock className="size-7 mx-auto text-primary mb-2" /><h3 className="font-display font-semibold">Nenhuma reunião solicitada</h3><p className="text-sm text-muted-foreground mt-1">Quando um Lançador demonstrar interesse, a operação organizará a agenda.</p></div> : minhasReunioes.map((reuniao) => <article key={reuniao.id} className="bg-card border border-border rounded-lg p-5 flex gap-4"><div className="size-11 shrink-0 rounded-md bg-primary/10 flex items-center justify-center"><CalendarClock className="size-5 text-primary" /></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-display font-semibold">{projeto.nome}</h3><BadgeStatus status={reuniao.status} /></div>{reuniao.agenda ? <p className="text-sm mt-2 flex items-center gap-1.5"><MapPin className="size-3.5 text-primary" />{reuniao.agenda.data} às {reuniao.agenda.horario} · {reuniao.agenda.local}</p> : <p className="text-sm text-muted-foreground mt-2">A equipe recebeu o interesse e está organizando a disponibilidade da Rodada.</p>}</div></article>)}</section>}
  </PainelLayout>;
}
