/** Painel do Administrador — operações persistentes da Rodada de Parcerias. */
import { useMemo, useState } from "react";
import PainelLayout from "@/components/PainelLayout";
import { BadgeStatus, ChecklistTriagem, Label } from "@/components/Compartilhados";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { trpc } from "@/lib/trpc";
import { CalendarClock, CheckCircle2, ClipboardCheck, FileCheck2, MapPin, UsersRound, XCircle } from "lucide-react";
import { toast } from "sonner";
import FluxoBpmn from "@/components/FluxoBpmn";

const areasAdmin = new Set(["inscricoes", "experts", "lancadores", "triagem", "agenda", "fluxo"]);
const statusProjeto = { draft: "Rascunho", submitted: "Em triagem", under_review: "Em triagem", eligible: "Elegível para catálogo", not_eligible: "Não elegível" } as const;
const statusInteresse = { declared: "Interesse declarado", requested: "Em organização", confirmed: "Reunião confirmada", closed: "Encerrado" } as const;

export default function AdminPainel({ onTrocarPapel }: { onTrocarPapel: (p: "admin" | "expert" | "lancador") => void }) {
  const [pagina, setPagina] = useState(() => { const area = new URLSearchParams(window.location.search).get("area"); return area && areasAdmin.has(area) ? area : "inscricoes"; });
  const [notasInscricao, setNotasInscricao] = useState<Record<number, string>>({});
  const [notasTriagem, setNotasTriagem] = useState<Record<number, string>>({});
  const [agendarId, setAgendarId] = useState<number | null>(null);
  const [dataHora, setDataHora] = useState("");
  const [local, setLocal] = useState("Rodada de Parcerias — Encontro Insider");
  const [notaOperacional, setNotaOperacional] = useState("");
  const registros = trpc.registration.all.useQuery(undefined, { retry: false });
  const projetos = trpc.projects.forAdmin.useQuery(undefined, { retry: false });
  const interesses = trpc.interests.forAdmin.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const revisarInscricao = trpc.registration.review.useMutation({ onSuccess: async () => { await Promise.all([utils.registration.all.invalidate(), utils.registration.pending.invalidate()]); toast.success("Decisão de participação registrada"); }, onError: erro => toast.error("Não foi possível registrar a decisão", { description: erro.message }) });
  const revisarProjeto = trpc.projects.review.useMutation({ onSuccess: async () => { await utils.projects.forAdmin.invalidate(); await utils.projects.catalog.invalidate(); toast.success("Triagem registrada", { description: "O status do projeto foi atualizado no catálogo curado." }); }, onError: erro => toast.error("Não foi possível concluir a triagem", { description: erro.message }) });
  const agendar = trpc.interests.schedule.useMutation({ onSuccess: async () => { await Promise.all([utils.interests.forAdmin.invalidate(), utils.interests.mineAsExpert.invalidate(), utils.interests.mineAsLauncher.invalidate()]); setAgendarId(null); toast.success("Reunião agendada"); }, onError: erro => toast.error("Não foi possível agendar a reunião", { description: erro.message }) });
  const pendentes = useMemo(() => (registros.data ?? []).filter(item => item.registration.status === "pending"), [registros.data]);
  const experts = useMemo(() => (registros.data ?? []).filter(item => item.registration.requestedRole === "expert"), [registros.data]);
  const lancadores = useMemo(() => (registros.data ?? []).filter(item => item.registration.requestedRole === "lancador"), [registros.data]);
  const emTriagem = useMemo(() => (projetos.data ?? []).filter(item => item.project.status === "submitted" || item.project.status === "under_review"), [projetos.data]);
  const interesseSelecionado = interesses.data?.find(item => item.interest.id === agendarId) ?? null;
  const navegar = (proxima: string) => { setPagina(proxima); const url = new URL(window.location.href); url.searchParams.set("area", proxima); window.history.replaceState({}, "", url); };
  const decidirInscricao = (id: number, decision: "approved" | "rejected") => { const note = notasInscricao[id]?.trim() ?? ""; if (note.length < 3) return toast.error("Registre uma observação antes de concluir"); revisarInscricao.mutate({ registrationId: id, decision, note }); };
  const decidirProjeto = (id: number, decision: "eligible" | "not_eligible") => { const observation = notasTriagem[id]?.trim() ?? ""; if (observation.length < 3) return toast.error("Registre uma observação da triagem"); revisarProjeto.mutate({ projectId: id, decision, observation, nicheReviewed: true, avatarReviewed: true, romaReviewed: true, maturityReviewed: true }); };
  const salvarAgenda = () => { if (!agendarId || !dataHora || local.trim().length < 2) return toast.error("Informe data, horário e local da reunião"); agendar.mutate({ interestId: agendarId, scheduledFor: new Date(dataHora), location: local.trim(), operationalNote: notaOperacional.trim() || undefined }); };

  return <PainelLayout papel="admin" onTrocarPapel={onTrocarPapel} nomeUsuario="Administrador" paginaAtiva={pagina} onNavegar={navegar}
    titulo={pagina === "inscricoes" ? "Inscrições pendentes" : pagina === "experts" ? "Experts cadastrados" : pagina === "lancadores" ? "Lançadores cadastrados" : pagina === "triagem" ? "Triagem manual" : pagina === "agenda" ? "Reuniões da Rodada" : "Fluxo operacional BPMN"}
    subtitulo={pagina === "inscricoes" ? "Aprove a participação antes de liberar o painel correspondente" : pagina === "experts" ? "Acompanhe as inscrições de Experts" : pagina === "lancadores" ? "Acompanhe as inscrições de Lançadores" : pagina === "triagem" ? "Avalie Nicho, Avatar, ROMA e maturidade sem score automatizado" : pagina === "agenda" ? "Acompanhe interesses e organize os horários presenciais" : "Modelagem BPMN do fluxo de parcerias validado pela operação"}>
    {pagina === "inscricoes" && <section className="space-y-4 rise-in"><Aviso icone={<ClipboardCheck className="size-5 text-primary shrink-0" />}>O link de cadastro é aberto à comunidade, mas <strong>nenhuma pessoa acessa os painéis antes da decisão da operação</strong>. Registre uma observação em toda aprovação ou devolução.</Aviso>{registros.isLoading ? <Estado texto="Carregando inscrições pendentes…" /> : registros.isError ? <Estado texto="Não foi possível carregar a fila agora." /> : pendentes.length === 0 ? <Estado texto="Nenhuma inscrição aguardando decisão." icone /> : pendentes.map(({ registration, user }) => <article key={registration.id} className="bg-card border border-primary/35 rounded-lg p-5"><div className="flex flex-col gap-5 lg:flex-row"><div className="size-11 rounded-md bg-primary/10 flex shrink-0 items-center justify-center"><UsersRound className="size-5 text-primary" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-semibold">{registration.fullName}</h2><BadgeStatus status={registration.requestedRole === "expert" ? "Expert" : "Lançador"} /></div><p className="mt-1 text-sm text-muted-foreground">{user.email || "E-mail não informado"}</p><dl className="mt-4 grid gap-x-6 gap-y-3 text-sm sm:grid-cols-2"><Dado rotulo="Telefone" valor={registration.phone || "Não informado"} /><Dado rotulo="Instagram" valor={registration.instagram || "Não informado"} /><Dado rotulo="Enviado em" valor={new Date(registration.createdAt).toLocaleString("pt-BR")} /></dl></div><div className="w-full space-y-3 lg:w-72"><textarea aria-label={`Registro da decisão de ${registration.fullName}`} value={notasInscricao[registration.id] ?? ""} onChange={event => setNotasInscricao(atual => ({ ...atual, [registration.id]: event.target.value }))} maxLength={2000} rows={3} className="w-full resize-y rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/60" placeholder="Registro da decisão*" /><div className="grid grid-cols-2 gap-2"><Button className="min-h-11" disabled={revisarInscricao.isPending} onClick={() => decidirInscricao(registration.id, "approved")}>Aprovar</Button><Button variant="outline" className="min-h-11 bg-card hover:bg-accent" disabled={revisarInscricao.isPending} onClick={() => decidirInscricao(registration.id, "rejected")}>Devolver</Button></div></div></div></article>)}</section>}
    {pagina === "experts" && <ListaParticipantes titulo="Experts" itens={experts} vazio="Nenhum Expert se cadastrou até o momento." />}
    {pagina === "lancadores" && <ListaParticipantes titulo="Lançadores" itens={lancadores} vazio="Nenhum Lançador se cadastrou até o momento." />}
    {pagina === "triagem" && <section className="space-y-4 rise-in"><Aviso icone={<FileCheck2 className="size-5 text-primary shrink-0" />}>Esta etapa não recomenda parceiros, não gera score e não envia propostas. Ela apenas determina se o projeto está completo e <strong>elegível para aparecer no catálogo</strong> dos Lançadores.</Aviso>{projetos.isLoading ? <Estado texto="Carregando projetos para triagem…" /> : projetos.isError ? <Estado texto="Não foi possível carregar os projetos." /> : emTriagem.length === 0 ? <Estado texto="Nenhum projeto aguardando triagem." icone /> : emTriagem.map(({ project, user }) => <article key={project.id} className="bg-card border border-primary/35 rounded-lg p-5"><div className="flex flex-col lg:flex-row gap-5"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-lg font-semibold">{project.name}</h3><BadgeStatus status="Em triagem" /></div><p className="text-sm text-muted-foreground">Expert: {user.name || "Participante"} · {project.niche}</p><p className="text-sm mt-3"><Label className="mr-2">ROMA</Label>{project.roma}</p><p className="text-sm mt-2"><Label className="mr-2">Avatar</Label>{project.avatarDescription}</p><div className="mt-4"><Label>Registro da triagem *</Label><textarea value={notasTriagem[project.id] ?? ""} onChange={event => setNotasTriagem(atual => ({ ...atual, [project.id]: event.target.value }))} className="mt-2 w-full resize-y rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/60" rows={3} placeholder="Descreva a decisão da operação" /></div></div><div className="w-full lg:w-52 space-y-3"><ChecklistTriagem triagem={{ nicho: true, avatar: true, roma: true, maturidade: true, observacao: "Confirme a leitura de cada critério antes de decidir." }} /><Button className="min-h-11 w-full gap-2" disabled={revisarProjeto.isPending} onClick={() => decidirProjeto(project.id, "eligible")}><CheckCircle2 className="size-4" />Marcar elegível</Button><Button variant="outline" className="min-h-11 w-full gap-2 bg-card hover:bg-accent" disabled={revisarProjeto.isPending} onClick={() => decidirProjeto(project.id, "not_eligible")}><XCircle className="size-4" />Não elegível</Button></div></div></article>)}</section>}
    {pagina === "agenda" && <section className="space-y-4 rise-in"><Aviso icone={<CalendarClock className="size-5 text-primary shrink-0" />}>Interesses declarados entram na fila operacional. A confirmação de mesa e horário é responsabilidade da equipe do evento.</Aviso>{interesses.isLoading ? <Estado texto="Carregando interesses declarados…" /> : interesses.isError ? <Estado texto="Não foi possível carregar a agenda." /> : interesses.data?.length === 0 ? <Estado texto="Nenhum interesse declarado até o momento." icone /> : interesses.data?.map(({ interest, project, registration, meeting }) => <article key={interest.id} className="bg-card border border-border rounded-lg p-5 flex flex-col md:flex-row md:items-center gap-4"><div className="size-11 rounded-md bg-primary/10 flex items-center justify-center"><CalendarClock className="size-5 text-primary" /></div><div className="flex-1"><div className="flex flex-wrap gap-2 items-center"><h3 className="font-display font-semibold">{project.name}</h3><BadgeStatus status={statusInteresse[interest.status]} /></div><p className="text-sm text-muted-foreground mt-1">Interesse de {registration.fullName}</p>{meeting ? <p className="text-sm mt-2 flex items-center gap-1.5"><MapPin className="size-3.5 text-primary" />{new Date(meeting.scheduledFor).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })} · {meeting.location}</p> : <p className="text-sm text-muted-foreground mt-2">Aguardando definição de horário e mesa.</p>}</div><Button variant={meeting ? "outline" : "default"} className="min-h-11 w-full md:w-auto" onClick={() => setAgendarId(interest.id)}>{meeting ? "Reagendar" : "Agendar"}</Button></article>)}</section>}
    {pagina === "fluxo" && <FluxoBpmn />}
    <Dialog open={!!interesseSelecionado} onOpenChange={() => setAgendarId(null)}><DialogContent><DialogHeader><DialogTitle className="font-display text-xl">Agendar reunião</DialogTitle><DialogDescription>{interesseSelecionado?.project.name} · interesse de {interesseSelecionado?.registration.fullName}</DialogDescription></DialogHeader><div className="space-y-4"><label className="block"><span className="label-ed">Data e horário *</span><input type="datetime-local" value={dataHora} onChange={event => setDataHora(event.target.value)} className="mt-2 min-h-11 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><label className="block"><span className="label-ed">Local *</span><input value={local} onChange={event => setLocal(event.target.value)} maxLength={180} className="mt-2 min-h-11 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><label className="block"><span className="label-ed">Nota operacional</span><textarea value={notaOperacional} onChange={event => setNotaOperacional(event.target.value)} rows={3} maxLength={2000} className="mt-2 w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="Mesa, ponto de encontro ou orientação para a equipe" /></label><Button className="w-full min-h-11" disabled={agendar.isPending} onClick={salvarAgenda}>Confirmar agendamento</Button></div></DialogContent></Dialog>
  </PainelLayout>;
}

function Aviso({ icone, children }: { icone: React.ReactNode; children: React.ReactNode }) { return <div className="bg-accent/50 border border-border rounded-lg p-4 flex gap-3">{icone}<p className="text-sm">{children}</p></div>; }
function Estado({ texto, icone }: { texto: string; icone?: boolean }) { return <div className="bg-card border border-border rounded-lg p-8 text-center">{icone && <CheckCircle2 className="size-7 mx-auto text-primary mb-2" />}<p className="text-sm text-muted-foreground">{texto}</p></div>; }
function Dado({ rotulo, valor }: { rotulo: string; valor: string }) { return <div><dt className="label-ed">{rotulo}</dt><dd className="mt-1">{valor}</dd></div>; }
function ListaParticipantes({ titulo, itens, vazio }: { titulo: string; itens: Array<{ registration: { id: number; fullName: string; status: "pending" | "approved" | "rejected"; phone: string | null; instagram: string | null; createdAt: Date }; user: { email: string | null } }>; vazio: string }) { const textoStatus = { pending: "Aguardando aprovação", approved: "Aprovado", rejected: "Devolvido" } as const; return <section className="space-y-4 rise-in"><Aviso icone={<UsersRound className="size-5 text-primary shrink-0" />}>Participantes de <strong>{titulo}</strong> e seus respectivos estados de participação na Rodada.</Aviso>{itens.length === 0 ? <Estado texto={vazio} icone /> : itens.map(({ registration, user }) => <article key={registration.id} className="bg-card border border-border rounded-lg p-5 flex flex-col sm:flex-row gap-4 sm:items-center"><div className="size-11 rounded-md bg-primary/10 flex shrink-0 items-center justify-center"><UsersRound className="size-5 text-primary" /></div><div className="flex-1"><div className="flex flex-wrap gap-2 items-center"><h2 className="font-display text-lg font-semibold">{registration.fullName}</h2><BadgeStatus status={textoStatus[registration.status]} /></div><p className="text-sm text-muted-foreground mt-1">{user.email || "E-mail não informado"}</p><p className="text-sm text-muted-foreground mt-2">{registration.instagram || "Sem Instagram"}{registration.phone ? ` · ${registration.phone}` : ""}</p></div></article>)}</section>; }
